import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  /*docs: [
    'intro',
    {
      type: 'category',
      label: 'AndroidTV',      // 主分类
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Android 14',      // 子分类
		  collapsible: true,
		  collapsed: false,
          items: [
			{
				type: 'autogenerated',
				dirName: 'android14',  // 自动扫描 android14 目录下的所有文件
			},
          ],
        },
        {
          type: 'category',
          label: 'Android 16',
          collapsible: true,
		  collapsed: false,
          items: [
			{
				type: 'autogenerated',
				dirName: 'android16',  // 自动扫描 android14 目录下的所有文件
			},
          ],
        },
      ],
    },
  ],*/
  /*docs: [
    'intro',
    // Android 14 分类
    {
      type: 'category',
      label: 'Android 14',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'android14',  // 自动生成 Android 14 下的所有文件
        },
      ],
    },
    // Android 16 分类
    {
      type: 'category',
      label: 'Android 16',
      collapsible: true,
      collapsed: true,  // 默认折叠
      items: [
        {
          type: 'autogenerated',
          dirName: 'android16',  // 自动生成 Android 16 下的所有文件
        },
      ],
    },
  ],*/
};

export default sidebars;
